apiVersion: apps/v1
kind: Deployment
metadata:
  name: aicoolgen-backend-deployment
  labels:
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aicoolgen-backend
  template:
    metadata:
      labels:
        app: aicoolgen-backend
    spec:
      containers:
      - name: backend
        image: ${ECR_REGISTRY}/ai-gen-app-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENAI_API_KEY
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGODB_URL
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUDINARY_API_SECRET
        resources:
          requests:
            memory: "128Mi"
            cpu:  "250m"
          limits:
            memory: "250Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: ecr-registry-secret
